import { AnimatePresence, motion } from "framer-motion";
import { ArrowRight, ChevronDown, CheckCircle2 } from "lucide-react";
import { useState } from "react";
import { faqs } from "../../data/data";
import { Button } from "../ui/button";

export function FaqCta() {
  const [open, setOpen] = useState(0);
  return <><section id="resources" className="section-space bg-white"><div className="naano-shell grid gap-12 lg:grid-cols-[0.8fr_1.2fr]"><div><h2 className="section-title max-w-md">Frequently asked questions.</h2><p className="section-copy mt-6 max-w-sm">Everything you need to know before getting started.</p><a href="#top" className="mt-10 inline-flex items-center gap-2 font-bold">Talk to our team <ArrowRight className="h-5 w-5" /></a></div><div>{faqs.map(([question, answer], index) => <div className="border-t border-sky-100 py-1" key={question}><button className="flex w-full items-center justify-between gap-5 py-6 text-left text-xl font-bold sm:text-2xl" onClick={() => setOpen(open === index ? -1 : index)} aria-expanded={open === index}>{question}<ChevronDown className={`h-5 w-5 shrink-0 transition-transform ${open === index ? "rotate-180" : ""}`} /></button><AnimatePresence initial={false}>{open === index && <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }} exit={{ height: 0, opacity: 0 }} transition={{ duration: 0.25 }} className="overflow-hidden"><p className="max-w-3xl pb-7 text-lg leading-8 text-muted-foreground">{answer}</p></motion.div>}</AnimatePresence></div>)}</div></div></section><section className="relative overflow-hidden bg-[linear-gradient(135deg,#e7f9ff,#f9feff_45%,#d9f4ff)] py-24 sm:py-32"><div className="naano-shell relative mx-auto max-w-4xl text-center"><p className="eyebrow text-blue-800">Ready to launch?</p><h2 className="section-title mt-6">Your next creator<br />campaign starts here.</h2><p className="section-copy mx-auto mt-6 max-w-2xl">Get a clear creator strategy, campaign format and estimated budget for your next launch.</p><div className="mx-auto mt-12 max-w-2xl rounded-[2rem] border border-white bg-white/85 p-7 text-left shadow-[0_28px_80px_hsl(var(--naano-shadow)/0.18)] sm:p-10"><div className="flex items-center gap-4"><div className="grid h-11 w-11 place-items-center rounded-full bg-slate-900 text-white">N</div><p className="eyebrow text-blue-800">Campaign strategy call</p></div><h3 className="mt-8 text-3xl font-black">30-minute working session</h3><p className="mt-3 text-lg text-muted-foreground">Leave with a concrete plan for your next creator campaign.</p><ul className="mt-7 divide-y divide-sky-100 border-y border-sky-100">{["Creator strategy", "Campaign format", "Budget recommendation"].map((item) => <li className="flex items-center gap-3 py-4" key={item}><CheckCircle2 className="h-5 w-5 text-blue-700" />{item}</li>)}</ul><Button size="lg" className="mt-8">Book a campaign call <ArrowRight className="ml-2 h-5 w-5" /></Button></div></div></section></>;
}
