import { motion } from "framer-motion";
import { ArrowRight, BadgeCheck } from "lucide-react";
import { LinkedinIcon } from "@/components/ui/linkedin-icon";

import { Button } from "@/components/ui/button";
import { navigationActions, siteConfig } from "@/data/data";
import { useMouseParallax } from "@/hooks/useMouseParallax";

import { TrustedLogos } from "./TrustedLogos";

export function Hero() {
  const { x, y } = useMouseParallax();

  const navigate = (href: string) => {
    window.location.href = href;
  };

  return (
    <section
      className="
        relative
        overflow-hidden
        border-b
        border-border/35
        bg-[#c9edff]
        py-20
        sm:py-28
        lg:py-32
      "
    >
      {/* Background clouds */}

      <motion.div
        className="
          cloud-orb
          cloud-orb-left
          pointer-events-none
        "
        animate={{
          x: x * 10,
          y: y * 6,
        }}
        transition={{
          type: "spring",
          stiffness: 35,
          damping: 20,
          mass: 0.8,
        }}
      />

      <motion.div
        className="
          cloud-orb
          cloud-orb-right
          pointer-events-none
        "
        animate={{
          x: x * -14,
          y: y * -8,
        }}
        transition={{
          type: "spring",
          stiffness: 30,
          damping: 22,
          mass: 0.9,
        }}
      />

      {/* Extra subtle cloud layer */}

      <motion.div
        className="
          absolute
          -left-20
          top-1/3
          h-72
          w-72
          rounded-full
          bg-white/40
          blur-3xl
          pointer-events-none
        "
        animate={{
          x: x * 7,
          y: y * 4,
        }}
        transition={{
          type: "spring",
          stiffness: 25,
          damping: 20,
        }}
      />

      <motion.div
        className="
          absolute
          -right-24
          top-1/2
          h-80
          w-80
          rounded-full
          bg-white/35
          blur-3xl
          pointer-events-none
        "
        animate={{
          x: x * -9,
          y: y * -5,
        }}
        transition={{
          type: "spring",
          stiffness: 25,
          damping: 20,
        }}
      />

      <div className="naano-shell relative z-10 text-center">
        {/* Eyebrow */}

        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{
            duration: 0.6,
            ease: [0.22, 1, 0.36, 1],
          }}
        >
          <div
            className="
              mx-auto
              inline-flex
              items-center
              gap-2
              rounded-full
              bg-white/90
              px-4
              py-2
              text-sm
              font-medium
              text-slate-700
              shadow-sm
              backdrop-blur-sm
            "
          >
            <span className="flex items-center gap-1.5">
              <span className="text-black">
                X
              </span>

              <LinkedinIcon 
                className="h-4 w-4"

              />
            </span>

            <span>
              Where B2B brands work with creators
            </span>
          </div>
        </motion.div>

        {/* Hero content */}

        <motion.div
          initial={{ opacity: 0, y: 18 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{
            duration: 0.7,
            delay: 0.08,
            ease: [0.22, 1, 0.36, 1],
          }}
        >
          <h1
            className="
              mx-auto
              mt-7
              max-w-5xl
              text-[3.4rem]
              font-bold
              leading-[0.98]
              tracking-[-0.055em]
              text-[hsl(var(--naano-ink))]
              sm:text-6xl
              md:text-7xl
              lg:text-[4.5rem]
            "
          >
            The B2B LinkedIn
            <br className="hidden md:block" />
            {" "}Creator Marketplace.
          </h1>

          <p
            className="
              mx-auto
              mt-7
              max-w-3xl
              text-base
              leading-7
              text-[hsl(var(--naano-copy))]
              sm:text-lg
              sm:leading-8
            "
          >
            Find the creators your buyers already trust,
            launch campaigns in days, and track the clicks,
            leads and pipeline generated by every post.
          </p>
        </motion.div>

        {/* CTA */}

        <motion.div
          initial={{ opacity: 0, y: 14 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{
            duration: 0.6,
            delay: 0.16,
            ease: [0.22, 1, 0.36, 1],
          }}
          className="
            mt-9
            flex
            flex-col
            items-center
            justify-center
            gap-3
            sm:flex-row
          "
        >
          <Button
            size="lg"
            onClick={() =>
              navigate("#launch-campaign")
            }
            className="
              h-14
              rounded-2xl
              bg-black
              px-7
              text-base
              font-medium
              text-white
              shadow-none
              transition-none
              hover:bg-black
              hover:text-white
            "
          >
            Launch a campaign

            <ArrowRight className="ml-2 h-5 w-5" />
          </Button>

          <Button
            variant="ghost"
            size="lg"
            onClick={() =>
              navigate("#how-it-works")
            }
            className="
              h-14
              rounded-2xl
              px-5
              text-base
              font-medium
              text-black
              shadow-none
              transition-none
              hover:bg-transparent
              hover:text-black
            "
          >
            See how Naano works

            <ArrowRight className="ml-2 h-5 w-5" />
          </Button>
        </motion.div>

        {/* Trust statement */}

        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{
            duration: 0.6,
            delay: 0.25,
          }}
          className="
            mt-9
            inline-flex
            items-center
            gap-2
            text-sm
            font-medium
            text-slate-600
          "
        >
          <BadgeCheck className="h-5 w-5" />

          <span>
            Trusted by modern B2B teams
          </span>
        </motion.div>

        {/* Moving logos */}

        <TrustedLogos />
      </div>
    </section>
  );
}