import { motion } from "framer-motion";
import { ArrowRight, Play } from "lucide-react";
import { results } from "../../data/data";

export function Proof() {
  return <><section className="section-space cloud-wash"><div className="naano-shell"><h2 className="section-title">Real teams. Measurable pipeline.</h2><p className="section-copy mt-5">See how B2B teams turn creator trust into attributable demand with Naano.</p><div className="mt-14 grid overflow-hidden rounded-[2rem] border border-sky-100 bg-white/75 lg:grid-cols-[0.85fr_1.15fr]"><div className="p-7 sm:p-11"><p className="eyebrow">Video testimonial</p><div className="relative mt-5 grid aspect-[4/3] place-items-center overflow-hidden rounded-[1.5rem] bg-[linear-gradient(135deg,#e9f6ff,#cdefff_45%,#e8e5ff)]"><div className="absolute inset-x-[36%] top-0 h-full bg-slate-800/20" /><button className="relative grid h-16 w-16 place-items-center rounded-full bg-white shadow-xl" aria-label="Play testimonial"><Play className="ml-1 h-6 w-6 fill-slate-900" /></button></div><p className="mt-7 text-2xl font-bold leading-tight">“Naano became one of our fastest ways to launch trusted content.”</p></div><div className="border-t border-sky-100 p-7 sm:p-11 lg:border-l lg:border-t-0"><div className="flex justify-between"><p className="eyebrow">Case study</p><span className="text-xl font-black">BlogSEO</span></div><h3 className="mt-10 max-w-xl text-3xl font-black leading-tight sm:text-4xl">How BlogSEO turned creator content into product signups</h3><p className="mt-5 max-w-xl text-lg leading-8 text-muted-foreground">BlogSEO briefed SEO & SaaS creators on LinkedIn and X, then traced every trial back to the post that drove it, all in Naano.</p><div className="mt-9 grid grid-cols-3 border-y border-sky-100 py-6"><Metric value="9" label="creators activated" /><Metric value="2,940" label="qualified clicks" /><Metric value="512" label="trials started" /></div><a className="mt-8 inline-flex items-center gap-2 font-bold" href="#resources">Read case study <ArrowRight className="h-5 w-5" /></a></div></div></div></section><section id="creators" className="section-space bg-white"><div className="naano-shell text-center"><p className="eyebrow"><span className="mr-2 inline-block h-2 w-2 rounded-full bg-sky-400" />The results</p><h2 className="section-title mt-6">Proven across thousands of campaigns.</h2><div className="mt-12 rounded-[2rem] bg-[linear-gradient(135deg,#eefbff,#f9fdff_60%,#e6f7ff)] p-5 sm:p-8"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{results.map((result, index) => <motion.div initial={{ opacity: 0, scale: 0.96 }} whileInView={{ opacity: 1, scale: 1 }} viewport={{ once: true }} transition={{ delay: index * 0.06 }} className="rounded-[1.35rem] bg-white/80 px-5 py-9" key={result.label}><strong className="text-5xl font-black sm:text-6xl">{result.value}</strong><p className="mt-3 text-muted-foreground">{result.label}</p></motion.div>)}</div></div></div></section></>;
}

function Metric({ value, label }: { value: string; label: string }) { return <div className="px-2 text-left first:border-r last:border-l border-sky-100"><strong className="block text-3xl font-black sm:text-5xl">{value}</strong><span className="mt-2 block text-sm text-muted-foreground">{label}</span></div>; }
