import type { IncomingMessage,ServerResponse } from "node:http";
import { randomUUID } from "node:crypto";
import { requireAuth } from "../middleware/authMiddleware";
import { db } from "../db/client";
import { error,json,readJson,stringValue,now } from "../utils/api";
function validWebsite(value:string){try{const url=new URL(value);return url.protocol==="https:"||url.protocol==="http:"?url:null}catch{return null}}
function extract(html:string){const title=html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]?.replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim()??"";const description=html.match(/<meta[^>]+name=["']description["'][^>]+content=["']([^"']*)["']/i)?.[1]??"";const og=html.match(/<meta[^>]+property=["']og:description["'][^>]+content=["']([^"']*)["']/i)?.[1]??description;const links=[...html.matchAll(/<a[^>]+href=["']([^"']+)["'][^>]*>/gi)].map(m=>m[1]).filter(v=>/(linkedin\.com|x\.com|twitter\.com)/i.test(v)).slice(0,10);return {title,description:og||description,socialLinks:links}}
export async function analyzeWebsite(request:IncomingMessage,response:ServerResponse){const user=requireAuth(request,response);if(!user)return;const body=await readJson(request);const website=stringValue(body.website);const target=validWebsite(website);if(!target)return error(response,422,"INVALID_WEBSITE","Enter a valid HTTP or HTTPS company website.");if(target.hostname==="localhost"||target.hostname.endsWith(".local")||/^127\.|^10\.|^192\.168\./.test(target.hostname))return error(response,422,"INVALID_WEBSITE","This website cannot be analyzed.");const id=randomUUID(),t=now();db.prepare("INSERT INTO website_analyses (id,user_id,website,status,created_at,updated_at) VALUES (?,?,?,?,?,?)").run(id,user.id,target.toString(),"processing",t,t);try{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),7000);const res=await fetch(target.toString(),{signal:controller.signal,headers:{"User-Agent":"NaanoCompanyAnalyzer/1.0"}});clearTimeout(timer);if(!res.ok)throw new Error(`Website returned HTTP ${res.status}.`);const contentType=res.headers.get("content-type")??"";if(!contentType.includes("text/html"))throw new Error("The website did not return an HTML page.");const html=(await res.text()).slice(0,1000000);const data=extract(html);const companyName=data.title.split("|")[0].split("—")[0].trim();db.prepare("UPDATE website_analyses SET status='completed',company_name=?,description=?,raw_title=?,raw_description=?,social_links=?,updated_at=? WHERE id=?").run(companyName,data.description,data.title,data.description,JSON.stringify(data.socialLinks),now(),id);return json(response,200,{data:db.prepare("SELECT * FROM website_analyses WHERE id=?").get(id)});}catch(e){const message=e instanceof Error?e.message:"Unable to analyze website.";db.prepare("UPDATE website_analyses SET status='failed',error_message=?,updated_at=? WHERE id=?").run(message,now(),id);return error(response,422,"WEBSITE_ANALYSIS_FAILED",message);}}
export function websiteAnalyses(request:IncomingMessage,response:ServerResponse){const user=requireAuth(request,response);if(!user)return;return json(response,200,{data:db.prepare("SELECT * FROM website_analyses WHERE user_id=? ORDER BY created_at DESC LIMIT 20").all(user.id)});}
