import { useState } from "react";
import { Formik, Form } from "formik";
import { Eye, EyeOff, Globe2, Linkedin, Building2, UserRound, BadgeCheck } from "lucide-react";
import { Link, Navigate, useNavigate } from "react-router-dom";
import { OnboardingShell } from "@/auth/components/OnboardingShell";
import { FieldError } from "@/auth/components/FieldError";
import { accountSchema, creatorDetailsSchema, creatorPositioningSchema, creatorPricingSchema, professionalSchema, brandCompanySchema, brandProfileSchema } from "@/auth/schemas";
import { saveBrandOnboarding, saveCreatorCard, saveCreatorDetails, saveCreatorProfessional, saveCreatorProfile, saveCreatorSocial } from "@/lib/onboarding";
import { register } from "@/lib/auth";
import { signIn } from "@/features/authSlice";
import { useAppDispatch, useAppSelector } from "@/store/hooks";

const industries=["AI","SaaS","Software","Developer Tools","Fintech","Cybersecurity","Marketing","Sales","Productivity","Data / Analytics","E-commerce","EdTech"];
const countries=["India","United States","United Kingdom","Germany","France","Canada","Australia","Singapore","Other"];
const stepsCreator=["Account","Social profiles","Positioning","Pricing","Professional"];
const stepsBrand=["Account","Company","Positioning","ICP & brief","Review"];

const initialValues={
 name:"",email:"",password:"",confirmPassword:"",role:"" as "creator"|"brand"|"",
 linkedinUrl:"",xProfileUrl:"",country:"",industries:[] as string[],headline:"",bio:"",priceCents:24000,
 registrationCountry:"",registeredBusiness:false,legalStatus:"individual",legalName:"",tradeName:"",panGstin:"",legalAddress:"",
 taxResponsibilityConfirmed:false,selfBillingMandateAccepted:false,certificationAccepted:false,
 website:"",companyName:"",description:"",valueProposition:"",icps:[{title:"",description:""},{title:"",description:""},{title:"",description:""}],brief:""
};

function Input({name,label,placeholder,type="text",formik}:{name:string;label:string;placeholder?:string;type?:string;formik:any}){return <label className="block"><span className="mb-2 block text-xs font-semibold tracking-wide text-[#626a78]">{label}</span><input name={name} type={type} value={formik.values[name]} onChange={formik.handleChange} onBlur={formik.handleBlur} placeholder={placeholder} className="auth-input"/><FieldError error={formik.errors[name]} touched={formik.touched[name]}/></label>}

export default function Register(){
 const dispatch=useAppDispatch();const navigate=useNavigate();const {isAuthenticated,isLoading}=useAppSelector(state=>state.auth);const [step,setStep]=useState(0);const [showPassword,setShowPassword]=useState(false);const [error,setError]=useState("");const [saving,setSaving]=useState(false);
 if(!isLoading&&isAuthenticated)return <Navigate to="/dashboard" replace/>;
 return <Formik initialValues={initialValues} onSubmit={()=>navigate("/dashboard",{replace:true})} validateOnBlur validateOnChange={false}>{formik=>{
 const role=formik.values.role;const steps=role==="brand"?stepsBrand:stepsCreator;
 const validateStep=async()=>{setError("");let schema:any;if(step===0)schema=accountSchema;else if(role==="creator"&&step===1)schema=creatorDetailsSchema.concat(creatorPositioningSchema.pick(["linkedinUrl"]));else if(role==="creator"&&step===2)schema=creatorPositioningSchema;else if(role==="creator"&&step===3)schema=creatorPricingSchema;else if(role==="creator"&&step===4)schema=professionalSchema;else if(role==="brand"&&step===1)schema=brandCompanySchema;else if(role==="brand"&&step===2)schema=brandProfileSchema;else schema=brandProfileSchema;try{await schema.validate(formik.values,{abortEarly:false});return true}catch(e:any){const next:any={};(e.inner??[]).forEach((item:any)=>{if(item.path)next[item.path]=item.message});formik.setErrors(next);Object.keys(next).forEach(key=>formik.setFieldTouched(key,true,false));return false}};
 const next=async()=>{if(!role&&step===0){setError("Choose Creator or Brand to continue.");return}if(!(await validateStep()))return;setSaving(true);try{
 if(step===0){const result=await register(formik.values.name,formik.values.email,formik.values.password,role as "creator"|"brand");dispatch(signIn(result.user));}
 else if(role==="creator"&&step===1)await saveCreatorSocial({linkedinUrl:formik.values.linkedinUrl,xProfileUrl:formik.values.xProfileUrl});
 else if(role==="creator"&&step===2)await saveCreatorProfile({headline:formik.values.headline,bio:formik.values.bio});
 else if(role==="creator"&&step===3)await saveCreatorCard({priceCents:formik.values.priceCents});
 else if(role==="creator"&&step===4)await saveCreatorProfessional(formik.values);
 else if(role==="brand"&&step>=1)await saveBrandOnboarding({...formik.values,step:step+1,icps:formik.values.icps.filter(item=>item.title)});
 if(step<steps.length-1)setStep(value=>value+1);else navigate("/dashboard",{replace:true});
 }catch(e){setError(e instanceof Error?e.message:"Unable to save this step.");}finally{setSaving(false)}};
 return <Form><OnboardingShell title={step===0?"Create your Naano account":role==="creator"?["Connect your professional profiles","Shape your creator positioning","Set your price per post","Complete professional information"][step-1]??"Your creator card": ["Tell us about your company","Define your positioning","Describe your ideal customers","Review your profile"][step-1]??"Your brand profile"} description={step===0?"Start with your account, then we'll build your marketplace profile with you.":role==="creator"?"Each step is saved to your account so you can return without losing progress.":"Give us the context brands and creators need to work with you."} steps={steps} current={step} canBack={step>0} canNext={!saving} nextLabel={step===steps.length-1?"Finish setup":"Continue"} onBack={()=>{setError("");setStep(value=>Math.max(0,value-1))}} onNext={next} saving={saving}>
 {step===0&&<div className="space-y-6"><div><p className="mb-3 text-sm font-semibold text-[#202124]">I am joining as</p><div className="grid gap-3 sm:grid-cols-2"><button type="button" onClick={()=>formik.setFieldValue("role","creator")} className={`rounded-2xl border p-5 text-left transition ${role==="creator"?"border-[#2864f0] bg-[#f3f7ff]":"border-[#e0e4ea] hover:border-[#c7ced9]"}`}><UserRound className="h-5 w-5 text-[#2864f0]"/><p className="mt-4 font-semibold">Creator</p><p className="mt-1 text-sm text-[#788192]">Find campaigns, publish content and get paid.</p></button><button type="button" onClick={()=>formik.setFieldValue("role","brand")} className={`rounded-2xl border p-5 text-left transition ${role==="brand"?"border-[#2864f0] bg-[#f3f7ff]":"border-[#e0e4ea] hover:border-[#c7ced9]"}`}><Building2 className="h-5 w-5 text-[#2864f0]"/><p className="mt-4 font-semibold">Brand</p><p className="mt-1 text-sm text-[#788192]">Find creators and launch campaigns.</p></button></div></div><Input name="name" label="Full name" placeholder="Chaitanya Shinde" formik={formik}/><Input name="email" label="Email" placeholder="you@example.com" type="email" formik={formik}/><label className="block"><span className="mb-2 block text-xs font-semibold tracking-wide text-[#626a78]">Password</span><div className="relative"><input name="password" value={formik.values.password} onChange={formik.handleChange} onBlur={formik.handleBlur} type={showPassword?"text":"password"} placeholder="At least 8 characters" className="auth-input pr-12"/><button type="button" onClick={()=>setShowPassword(v=>!v)} className="absolute right-4 top-1/2 -translate-y-1/2 text-[#9ba0a8]">{showPassword?<EyeOff className="h-5 w-5"/>:<Eye className="h-5 w-5"/>}</button></div><FieldError error={formik.errors.password} touched={formik.touched.password}/></label><Input name="confirmPassword" label="Confirm password" placeholder="Repeat your password" type="password" formik={formik}/></div>}
 {role==="creator"&&step===1&&<div className="space-y-5"><div className="rounded-2xl border border-[#dbe7ff] bg-[#f5f8ff] p-5"><div className="flex items-center gap-2 font-semibold"><BadgeCheck className="h-5 w-5 text-[#2864f0]"/>Connect your professional presence</div><p className="mt-2 text-sm leading-6 text-[#687387]">Add public profile URLs now. OAuth connections can be enabled once provider credentials are configured.</p></div><Input name="linkedinUrl" label="LinkedIn profile" placeholder="https://linkedin.com/in/yourname" formik={formik}/><Input name="xProfileUrl" label="X profile" placeholder="https://x.com/yourhandle" formik={formik}/><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-[#e4e8ee] p-4"><Linkedin className="h-5 w-5 text-[#0a66c2]"/><p className="mt-2 text-sm font-semibold">LinkedIn connection</p><p className="mt-1 text-xs text-[#7a8392]">We'll show a connected state after OAuth is configured.</p></div><div className="rounded-xl border border-[#e4e8ee] p-4"><Globe2 className="h-5 w-5 text-[#2864f0]"/><p className="mt-2 text-sm font-semibold">X connection</p><p className="mt-1 text-xs text-[#7a8392]">Your public handle remains editable.</p></div></div></div>}
 {role==="creator"&&step===2&&<div className="space-y-5"><Input name="headline" label="Professional headline" placeholder="AI & Full Stack Engineer" formik={formik}/><label className="block"><span className="mb-2 block text-xs font-semibold tracking-wide text-[#626a78]">About you</span><textarea name="bio" value={formik.values.bio} onChange={formik.handleChange} onBlur={formik.handleBlur} rows={7} placeholder="Tell brands what you build, who you help and what you can credibly talk about." className="w-full resize-none rounded-xl border border-[#d5d9df] p-4 text-[15px] outline-none focus:border-[#2864f0] focus:ring-2 focus:ring-[#2864f0]/10"/><FieldError error={formik.errors.bio} touched={formik.touched.bio}/></label></div>}
 {role==="creator"&&step===3&&<div className="space-y-6"><div className="rounded-3xl border border-[#e2e7ef] bg-[#fafbfe] p-8 text-center"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#2864f0]">Your price per post</p><div className="mt-5 flex items-center justify-center gap-2"><span className="text-3xl text-[#7d8491]">€</span><input name="priceCents" type="number" value={formik.values.priceCents/100} onChange={e=>formik.setFieldValue("priceCents",Math.round(Number(e.target.value)*100))} className="w-40 bg-transparent text-center text-6xl font-semibold tracking-[-.06em] outline-none"/></div><p className="mt-3 text-sm text-[#7b8493]">You can change your rate later from your marketplace profile.</p></div><label className="block"><span className="mb-2 block text-xs font-semibold text-[#626a78]">Country</span><select name="country" value={formik.values.country} onChange={formik.handleChange} className="auth-input"><option value="">Select your country</option>{countries.map(c=><option key={c}>{c}</option>)}</select><FieldError error={formik.errors.country} touched={formik.touched.country}/></label><div><p className="mb-2 text-xs font-semibold tracking-wide text-[#626a78]">Industries <span className="font-normal text-[#9aa1af]">(choose up to 3)</span></p><div className="flex flex-wrap gap-2">{industries.map(item=>{const selected=formik.values.industries.includes(item);return <button key={item} type="button" onClick={()=>formik.setFieldValue("industries",selected?formik.values.industries.filter(x=>x!==item):formik.values.industries.length<3?[...formik.values.industries,item]:formik.values.industries)} className={`rounded-full border px-3 py-2 text-xs font-medium ${selected?"border-[#2864f0] bg-[#eef4ff] text-[#245bdc]":"border-[#dfe3e9] text-[#737c8d]"}`}>{item}</button>})}</div><FieldError error={formik.errors.industries} touched={formik.touched.industries}/></div></div>}
 {role==="creator"&&step===4&&<div className="space-y-5"><Input name="registrationCountry" label="Registration country" placeholder="India" formik={formik}/><Input name="legalName" label="Legal name" placeholder="Full legal name or company name" formik={formik}/><Input name="legalAddress" label="Legal address" placeholder="Full billing address" formik={formik}/><label className="block"><span className="mb-2 block text-xs font-semibold text-[#626a78]">Legal status</span><select name="legalStatus" value={formik.values.legalStatus} onChange={formik.handleChange} className="auth-input"><option value="individual">Individual</option><option value="company">Company</option><option value="sole_proprietorship">Sole proprietorship</option></select></label>{[["taxResponsibilityConfirmed","I confirm I am responsible for declaring and paying applicable taxes."],["selfBillingMandateAccepted","I accept the self-billing mandate."],["certificationAccepted","I certify the professional information is accurate."]].map(([name,text])=><label key={name} className="flex gap-3 rounded-xl border border-[#e4e8ee] p-4 text-sm text-[#555e6e]"><input type="checkbox" name={name} checked={Boolean(formik.values[name])} onChange={formik.handleChange} className="mt-1 h-4 w-4"/><span>{text}<FieldError error={formik.errors[name]} touched={formik.touched[name]}/></span></label>)}</div>}
 {role==="brand"&&step===1&&<div className="space-y-5"><Input name="website" label="Company website" placeholder="https://yourcompany.com" formik={formik}/><div className="rounded-2xl border border-[#dbe7ff] bg-[#f5f8ff] p-5"><p className="font-semibold">We'll turn your website into a draft company profile.</p><p className="mt-1 text-sm leading-6 text-[#697487]">Company name, description, positioning, industries and audience signals can be reviewed before anything is saved as final.</p></div></div>}
 {role==="brand"&&step===2&&<div className="space-y-5"><Input name="companyName" label="Company name" placeholder="Acme AI" formik={formik}/><label className="block"><span className="mb-2 block text-xs font-semibold text-[#626a78]">Description</span><textarea name="description" value={formik.values.description} onChange={formik.handleChange} rows={4} className="w-full rounded-xl border border-[#d5d9df] p-4 outline-none focus:border-[#2864f0]"/></label><label className="block"><span className="mb-2 block text-xs font-semibold text-[#626a78]">Value proposition</span><textarea name="valueProposition" value={formik.values.valueProposition} onChange={formik.handleChange} rows={5} className="w-full rounded-xl border border-[#d5d9df] p-4 outline-none focus:border-[#2864f0]"/></label><Input name="country" label="Country" placeholder="India" formik={formik}/></div>}
 {role==="brand"&&step===3&&<div className="space-y-5"><p className="text-sm text-[#697487]">Add the audiences your creators need to understand. These become the foundation for creator briefs.</p>{formik.values.icps.map((item,index)=><div key={index} className="rounded-2xl border border-[#e3e7ed] p-4"><input value={item.title} onChange={e=>{const next=[...formik.values.icps];next[index]={...next[index],title:e.target.value};formik.setFieldValue("icps",next)}} placeholder={`ICP ${index+1} title`} className="w-full border-0 p-1 font-semibold outline-none"/><textarea value={item.description} onChange={e=>{const next=[...formik.values.icps];next[index]={...next[index],description:e.target.value};formik.setFieldValue("icps",next)}} placeholder="Who are they and what do they care about?" rows={2} className="mt-2 w-full resize-none border-0 p-1 text-sm outline-none"/></div>)}</div>}
 {role==="brand"&&step===4&&<div className="space-y-4"><div className="rounded-2xl bg-[#f5f8ff] p-6"><p className="text-xs font-bold uppercase tracking-[.15em] text-[#2864f0]">Ready to launch</p><p className="mt-3 text-2xl font-semibold tracking-[-.03em]">{formik.values.companyName||"Your company"}</p><p className="mt-2 text-sm leading-6 text-[#687386]">{formik.values.valueProposition||"Your value proposition will appear here."}</p></div><p className="text-sm text-[#737c8d]">Your profile will be saved and you can refine your ICP and creator brief from the workspace.</p></div>}
 {error&&<p role="alert" className="mt-4 rounded-xl bg-red-50 px-4 py-3 text-sm font-medium text-red-700">{error}</p>}
 </OnboardingShell></Form>}}</Formik>
}
