export const siteConfig = {
  name: "naano",
  tagline: "Turn LinkedIn creators into your best acquisition channel.",
};

export const heroSection = {
  eyebrow: "Where B2B brands work with creators",
  title: "The B2B LinkedIn Creator Marketplace.",
  description: "Find the creators your buyers already trust, launch campaigns in days, and track the clicks, leads and pipeline generated by every post.",
  trustStatement: "Trusted by modern B2B teams",
  primaryAction: {
    label: "Launch a campaign",
    href: "#launch-campaign",
  },
  secondaryAction: {
    label: "See how Naano works",
    href: "#how-it-works",
  },
} as const; 
export const navItems = [
  {
    label: "For companies",
    href: "#companies",
  },
  {
    label: "For creators",
    href: "#creators",
  },
  {
    label: "For agencies",
    href: "#agencies",
  },
  {
    label: "How it works",
    href: "#how-it-works",
  },
];

export const resourceLinks = [
  {
    label: "Blog",
    href: "#blog",
  },
  {
    label: "Customer stories",
    href: "#customer-stories",
  },
  {
    label: "Resources",
    href: "#resources",
  },
];

export const navigationActions = {
  language: {
    label: "EN",
    href: "#language",
    ariaLabel: "Change language",
  },

  resources: {
    label: "Resources",
    href: "#resources",
  },

  signIn: {
    label: "Sign in",
    href: "#sign-in",
  },

  signUp: {
    label: "Sign up",
    href: "#sign-up",
  },

  mobileMenu: {
    label: "Open navigation menu",
    closeLabel: "Close navigation menu",
  },
};

export const featuredTestimonial = {
  company: {
    name: "Zmirov Communication",
    logo: "/src/assets/logos/zmirov-communication.png",
  },

  quote: {
    before:
      "We manage €10M+ of influence budget every year. For B2B, Naano simply makes our life",
    highlight: "easier",
    closingQuote: '"',
  },

  person: {
    name: "David Zmirov",
    role: "CEO, Zmirov Communication",
    category: "Influence agency",
    image: "/src/assets/testimonials/david-zmirov.png",
  },
};

export const marketplaceSection = {
  eyebrow: "The Naano creator marketplace",

  title: "Work with all the best creators.",

  description:
    "Find the right B2B voices, compare their audience fit, and book every collaboration from one place.",

  image: "/src/assets/images/marketplace.png",

  imageAlt: "Naano creator marketplace",
};

export const proofSection = {
  title: "Real teams. Measurable pipeline.",
  description:
    "See how B2B teams turn creator trust into attributable demand with Naano.",

  video: {
    eyebrow: "VIDEO TESTIMONIAL",
    duration: "2:40",

    quote:
      "“Naano became one of our fastest acquisition channels. We know exactly what every creator brings.”",

    person: {
      name: "Vincent Josse",
      role: "CEO & Founder, BlogSEO",
      image: "/src/assets/testimonials/vincent-josse.png",
    },
  },

  caseStudy: {
    eyebrow: "CASE STUDY",
    company: "BlogSEO",

    title:
      "How BlogSEO turned creator content into product signups",

    description:
      "BlogSEO briefed SEO & SaaS creators on LinkedIn and X, then traced every trial back to the post that drove it, all in Naano.",

    metrics: [
      {
        value: "9",
        label: "creators activated",
      },
      {
        value: "2,940",
        label: "qualified clicks",
      },
      {
        value: "512",
        label: "trials started",
      },
    ],

    cta: "Read case study",

    trustedEyebrow: "TRUSTED BY TEAMS AT",

    trustedLogos: [
      "lemlist",
      "folk.",
      "LEADbay",
      "ringover",
      "attio",
      "La Growth Machine",
      "gojiberry",
      "ChatSEO",
      "Abyssale",
    ],

    additionalCount: "+30",
  },
} as const;
export const footerGroups = [
  {
    title: "Product",
    links: [
      "Features",
      "Pricing",
      "FAQs",
      "Blog",
      "Reports & benchmarks",
      "About",
    ],
  },

  {
    title: "Company",
    links: [
      "Help Center",
      "Privacy",
      "Terms of Sale & Use",
    ],
  },

  {
    title: "Press",
    links: [
      "Interview Thomas Marcelle, Xymag.tv",
      "Naano on FounderTrace",
      "Naano on TechnicalBeep",
    ],
  },

  {
    title: "Resources",
    links: [
      "LinkedIn creator marketplace",
      "B2B influencer marketing cost",
      "Creator Marketplace explained",
      "Naano vs alternatives",
      "Creator-led growth for B2B",
      "LinkedIn Ads vs creator-led CPL",
    ],
  },
];

export const trustLogos = [
  "attio",
  "La Growth Machine",
  "goji berry",
  "ChatSEO",
  "Abyssale",
];

export const workflowSteps = [
  {
    number: "01",
    title: "Find creators your buyers trust",
    visual: {
      type: "creators",
      creators: [
        {
          name: "Eric",
          fit: "92%",
          image: "/src/assets/images/workflowimages/eric.png",
        },
        {
          name: "Robin",
          fit: "88%",
          image: "/src/assets/images/workflowimages/robin.png",
        },
        {
          name: "Aya",
          fit: "84%",
          image: "/src/assets/images/workflowimages/aya.png",
        },
      ],
    },
  },

  {
    number: "02",
    title: "Build a campaign brief in minutes",
    visual: {
      type: "brief",
      badge: "AI",
      items: [
        "Objectives and key messages",
        "Creator guidelines",
        "Tracking links ready",
      ],
      progress: 72,
    },
  },

  {
    number: "03",
    title: "Manage every collaboration",
    visual: {
      type: "collaboration",
      creators: [
        {
          name: "Raphael",
          status: "Draft ready",
          image: "/src/assets/images/workflowimages/raphael.png",
        },
        {
          name: "Thomas",
          status: "Scheduled",
          image: "/src/assets/images/workflowimages/thomas.png",
        },
        {
          name: "Nada",
          status: "Live",
          image: "/src/assets/images/workflowimages/nada.png",
        },
      ],
    },
  },

  {
    number: "04",
    title: "Track reach, clicks, and leads",
    visual: {
      type: "results",
      label: "Attributed pipeline",
      value: "€48.2K",
      change: "+24%",
      views: "124K views",
      leads: "418 leads",
      bars: [30, 42, 35, 55, 70, 88, 100],
    },
  },

  {
    number: "05",
    title: "Pay creators without the admin",
    visual: {
      type: "payment",
      title: "Payment scheduled",
      subtitle: "Handled by Naano",
      payoutLabel: "Creator payout",
      payout: "€1,240",
      actions: ["Contract", "Invoice", "Payout"],
    },
  },
] as const;

export const workflowSection = {
  eyebrow: "One platform, from brief to results",

  title: "Run creator campaigns from one place.",

  description:
    "Find the right voices, launch faster, and connect every post to measurable business results.",
};

export const results = [
  {
    value: "5M+",
    label: "Impressions generated",
  },

  {
    value: "30K+",
    label: "Leads generated",
  },

  {
    value: "2,000+",
    label: "Creators on Naano",
  },

  {
    value: "5K+",
    label: "Posts published",
  },
];

export const creatorPosts = [
  {
    id: "thomas",

    name: "Thomas Higadère",

    role: "Creator · B2B & AI · 34K followers",

    avatar: "thomas.png",

    postImage: "post1.png",

    text:
      "How AI changed our prospecting workflow for wealth managers and private bankers.",

    metrics: {
      impressions: "42.8K",
      clicks: "312",
      leads: "18",
    },

    company: "lemlist",

    companyLogo: "lemlist.png",
  },

  {
    id: "robin",

    name: "Robin Tempe",

    role: "Creator · Sales & AI · 12K followers",

    avatar: "robin.png",

    postImage: "post2.png",

    text:
      "I run my entire prospecting workflow through an AI. Here is how.",

    metrics: {
      impressions: "9K",
      clicks: "100",
      leads: "50",
    },

    company: "LEADBay",

    companyLogo: "leadbay.png",
  },

  {
    id: "eric",

    name: "Eric Djavid",

    role: "Sales Leader · B2B · 40K followers",

    avatar: "eric.png",

    postImage: "post3.png",

    text:
      "Most sales teams spend 80% of their time on the wrong leads. Here is how I changed that.",

    metrics: {
      impressions: "20K",
      clicks: "350",
      leads: "80",
    },

    company: "LEADBay",

    companyLogo: "leadbay.png",
  },

  {
    id: "marina",

    name: "Marina Panova",

    role: "Content Creator · B2B · 34K followers",

    avatar: "nada.png",

    postImage: "post4.png",

    text:
      "How I build my 30-day LinkedIn content system, the exact playbook.",

    metrics: {
      impressions: "100K",
      clicks: "1,600",
      leads: "320",
    },

    company: "Abyssale",

    companyLogo: "abyssale.png",
  },
] as const;

export const finalCta = {
  eyebrow: "READY TO LAUNCH?",
  title: ["Your next creator", "campaign starts here."],
  description: "Get a clear creator strategy, campaign format and estimated budget for your next launch.",
  card: {
    eyebrow: "CAMPAIGN STRATEGY CALL",
    title: "30-minute working session",
    description: "Leave with a concrete plan for your next creator campaign.",
    items: ["Creator strategy", "Campaign format", "Budget recommendation"],
    primaryAction: "Book a campaign call",
    helperText: "Pick a time on the next page.",
    secondaryPrefix: "Prefer to start yourself?",
    secondaryAction: "Start for free",
  },
  trustText: "Trusted by B2B teams building creator-led acquisition.",
} as const;

export const pricingPlans = [
  {
    eyebrow: "Self-serve",

    title: "Run it yourself.",

    copy:
      "For teams that want the infrastructure to run creator campaigns in-house.",

    price: "€0",

    priceNote: "/ month",

    features: [
      "Creator marketplace access",
      "AI-powered brief creation",
      "Track clicks, companies and pipeline",
      "Automatic creator payouts",
    ],

    action: "Start for free",
  },

  {
    eyebrow: "Managed campaigns",

    title: "Get your time back.",

    copy:
      "For teams that want Naano to operate their creator channel end to end.",

    price: "Custom quote",

    features: [
      "Campaign strategy and positioning",
      "Creator sourcing and coordination",
      "Brief creation and campaign launch",
      "Reporting and optimisation",
    ],

    action: "Book a campaign call",
  },
];

export const faqs = [
  [
    "What is Naano?",
    "Naano is a B2B LinkedIn creator marketplace where teams discover and book vetted creators for sponsored campaigns, with every collaboration measured from reach to pipeline.",
  ],

  [
    "How does Naano find the right creators?",
    "We match creators on audience relevance, topic expertise, geography and the goals of your campaign.",
  ],

  [
    "Which networks do you support?",
    "Naano is built for B2B LinkedIn creator campaigns.",
  ],

  [
    "How does per-post pricing work?",
    "Each creator sets a clear, fixed price per post before you book.",
  ],

  [
    "How does attribution work?",
    "Campaign links and reporting connect engagement to clicks, qualified leads and pipeline.",
  ],
] as const;

export const authPages = {
  login: {
    title: "Welcome back",
    subtitle: "Sign in to your account",
    linkedin: "Continue with LinkedIn",
    google: "Continue with Google",
    divider: "OR CONTINUE WITH EMAIL",
    emailLabel: "EMAIL",
    emailPlaceholder: "john@company.com",
    passwordLabel: "PASSWORD",
    passwordPlaceholder: "••••••••",
    forgotPassword: "Forgot password?",
    submit: "Sign in",
    footerPrefix: "Don't have an account?",
    footerAction: "Sign up",
    footerHref: "/register",
    sideTitle: "Welcome back.",
    sideDescription: "Sign in to manage your campaigns, creators and payouts, all in one place.",
  },
  register: {
    title: "Create your account",
    subtitle: "First, who are you here as?",
    creator: {
      title: "I'm a creator",
      description: "Get paid to create LinkedIn content for B2B brands you actually use.",
    },
    brand: {
      title: "I'm a brand",
      description: "Find creators, launch campaigns, and trace real pipeline back to each post.",
    },
    footerPrefix: "Already have an account?",
    footerAction: "Sign in",
    footerHref: "/login",
    sideTitle: "One platform. Two sides.",
    sideDescription: "Creators get paid to post. B2B brands get real pipeline. Pick where you fit and we'll set the rest up in a couple of minutes.",
  },
} as const; 

export const authContent = {
  login: {
    logoLabel: "Naano",
    language: "EN",
    title: "Welcome back",
    subtitle: "Sign in to your account",
    social: {
      linkedin: "Continue with LinkedIn",
      google: "Continue with Google",
    },
    divider: "OR CONTINUE WITH EMAIL",
    emailLabel: "EMAIL",
    emailPlaceholder: "john@company.com",
    passwordLabel: "PASSWORD",
    passwordPlaceholder: "••••••••",
    forgotPassword: "Forgot password?",
    submit: "Sign in",
    footerPrefix: "Don't have an account?",
    footerAction: "Sign up",
    footerHref: "/register",
    panelTitle: "Welcome back.",
    panelDescription: "Sign in to manage your campaigns, creators and payouts, all in one place.",
  },
  register: {
    logoLabel: "Naano",
    language: "EN",
    title: "Create your account",
    subtitle: "First, who are you here as?",
    roles: [
      {
        id: "creator",
        title: "I'm a creator",
        description: "Create content and collaborate with B2B brands.",
      },
      {
        id: "brand",
        title: "I'm a brand",
        description: "Find creators and launch your next campaign.",
      },
    ],
    footerPrefix: "Already have an account?",
    footerAction: "Sign in",
    footerHref: "/login",
    panelTitle: "One platform. Two sides.",
    panelDescription: "Connect B2B brands and creators in one place to build campaigns that drive real results.",
  },
  chat: {
    prompt: "What would you like to see?",
  },
} as const;